//empty for now
const usernames = [
    'Ajax',
    'BigBubba',
    'ChromeDragon',
    'Dangername',
    'Excelsior86',
    'FreakMind',
    'GentleBunni',
    'HighRollrz',
    'Incogneato',
    'Jack',
    'KK_Uncle',
    'Lolnoob',
    'Marilyn',
    'Norris73',
    'Opps',
    'Problematique',
    'Q',
    'Riskyy',
    'Steve',
    'Turnover_Rate',
    'UltraViolet',
    'Violet',
    'Wisconson_Jones',
    'xXSniperWolfXx',
    'Yellow_Sub',
    'Zoinks',
];

const emails = [
    'ponies@farm.com',
    'illuminati@conspiracy.gov',
    'bonzai@tree.edu',
    'socmediaperson@totesreal.com',
    'random@email.com',
    'runningoutofemails@help.com',
    'email@placeholder.com',
    'myrealemail@true.com',
    'mafia@crime.org',
    'boooom@dabomb.com',
    'needmoreemails@neverends.com',
    'loremipsum@programming.edu',
    'lastemail@finally.com',
];

const thoughts = [
    'What should I have for lunch?',
    'Politics r complicated',
    'This is a thought',
    'I hope this thought is generated by the app',
    'Hello world, this is a comment',
    'Social media is a big waste of time',
    'Notes is my most used app',
    'Messages is open on my computer 24/7',
    'Email is open on my computer',
    'Compass is never opened',
    'Firefox is great for privacy',
    'Honey, Where arrrrrre my paaants?!',
];

const reactions = [
    'like',
    'favorite',
    'subscribe',
    'repost',
    'laughed',
    'loved',
];

const genRandomIndex = (arr) => Math.floor(Math.random() * arr.length);

const getRandomArrItem = (arr) => arr[Math.floor(Math.random() * arr.length)];

//there was extra randomization code on the activity but idk if i need it
const getRandomUserName = () => `${getRandomArrItem(usernames)}`;

const getRandomEmail = () => `${getRandomArrItem(emails)}`;

const getRandomThought = () => `${getRandomArrItem(thoughts)}`;

const getRandomReaction = () => `${getRandomArrItem(reactions)}`;

module.exports = {
    genRandomIndex,
    getRandomUserName,
    getRandomEmail,
    getRandomThought,
    getRandomReaction,
};