//empty for now
const usernames = [
    'Ajax',
    'BigBubba',
    'ChromeDragon',
    'Dangername',
    'Excelsior86',
    'FreakMind',
    'GentleBunni',
    'HighRollrz',
    'Incogneato',
    'Jack',
    'KK_Uncle',
    'Lolnoob',
    'Marilyn',
    'Norris73',
    'Opps',
    'Problematique',
    'Q',
    'Riskyy',
    'Steve',
    'Turnover_Rate',
    'UltraViolet',
    'Violet',
    'Wisconson_Jones',
    'xXSniperWolfXx',
    'Yellow_Sub',
    'Zoinks',
];

const thoughts = [
    'What should I have for lunch?',
    'Politics r complicated',
    'This is a thought',
    'I hope this thought is generated by the app',
    'Hello world, this is a comment',
    'Social media is a big waste of time',
    'Notes is my most used app',
    'Messages is open on my computer 24/7',
    'Email is open on my computer',
    'Compass is never opened',
    'Firefox is great for privacy',
    'Honey, Where arrrrrre my paaants?!',
];

const genRandomIndex = (arr) => Math.floor(Math.random() * arr.length);

const getRandomArrItem = (arr) => arr[Math.floor(Math.random() * arr.length)];

//there was extra randomization code on the activity but idk if i need it
const getRandomUserName = () => `${getRandomArrItem(usernames)}`;

module.exports = {
    genRandomIndex,
    getRandomUserName,
};